window.onload=function(){
    /*alert(2)*/
    /*setTimeout(function(){
        $('.helpRight-bottom>div').hover(function(){
            $(this).find('.help-pro').show(100)
            $(this).css({'background':'#eee','padding-bottom':'15px'})
        },function(){
            $(this).find('.help-pro').hide(100)
            $(this).css({'background':'#eee','padding-bottom':'0px'})
        })
    },2000)*/
}
